name: Bandit Python Code Scan

on:
  pull_request:
    branches:
      - main

jobs:
  bandit-scan:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    # Fetch only the pull request changes
    - name: Fetch PR changes
      run: git fetch origin +refs/pull/${{ github.event.pull_request.number }}/merge

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install Bandit
      run: pip install bandit

    - name: Run Bandit
      id: bandit_scan
      run: |
        ls -la ${{ github.workspace }}
        ls -la ${{ github.workspace }}/${{ github.event.pull_request.head.ref }}
        PR_PATH="${{ github.workspace }}/${{ github.event.pull_request.head.ref }}"
        echo "File path to be scanned: $PR_PATH"
        cat "$PR_PATH"  # Display the content of the file
        bandit -r "$PR_PATH" -f json -o bandit_output.json || true
        cat bandit_output.json

    - name: Analyze Bandit Results
      id: analyze_results
      run: |
        CRITICAL_ISSUES=$(jq '[.results[] | select(.issue_severity=="CRITICAL") ] | length' bandit_output.json)
        HIGH_ISSUES=$(jq '[.results[] | select(.issue_severity=="HIGH") ] | length' bandit_output.json)

        echo "Critical Issues: $CRITICAL_ISSUES"
        echo "High Issues: $HIGH_ISSUES"
        
        if [ "$CRITICAL_ISSUES" -gt 0 ] || [ "$HIGH_ISSUES" -gt 0 ]; then
          echo "status=block" >> $GITHUB_ENV
        else
          echo "status=success" >> $GITHUB_ENV
        fi

    - name: Add Comment and Block PR
      if: env.status == 'block'
      run: |
        gh pr comment ${{ github.event.pull_request.number }} --body 'Block'
        gh pr close ${{ github.event.pull_request.number }}
      env:
        GH_TOKEN: ${{ secrets.netsk }}

    - name: Add Comment and Merge PR
      if: env.status == 'success'
      run: |
        gh pr comment ${{ github.event.pull_request.number }} --body 'Successful'
        gh pr merge ${{ github.event.pull_request.number }} --merge
      env:
        GH_TOKEN: ${{ secrets.netsk }}
