name: Bandit Code Scan

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  bandit-scan:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install Bandit
      run: |
        python -m pip install --upgrade pip
        pip install bandit

    - name: Run Bandit
      id: bandit_scan
      run: |
        bandit -r . -f json -o bandit_output.json
        cat bandit_output.json

    - name: Analyze Bandit Results
      id: analyze_results
      run: |
        CRITICAL_FOUND=$(jq '.results[] | select(.issue_severity=="CRITICAL")' bandit_output.json)
        if [ -n "$CRITICAL_FOUND" ]; then
          echo "critical_found=true" >> $GITHUB_ENV
        else
          echo "critical_found=false" >> $GITHUB_ENV
        fi

    - name: Comment on PR
      if: env.critical_found == 'true'
      uses: actions/github-script@v6
      with:
        script: |
          github.issues.createComment({
            issue_number: context.issue.number,
            body: 'Block: Critical vulnerability found.'
          })

    - name: Fail if Critical Found
      if: env.critical_found == 'true'
      run: exit 1

    - name: Auto-merge PR
      if: env.critical_found == 'false'
      uses: actions/github-script@v6
      with:
        script: |
          github.pulls.merge({
            owner: context.repo.owner,
            repo: context.repo.repo,
            pull_number: context.issue.number,
            merge_method: 'merge'
          })
          github.issues.createComment({
            issue_number: context.issue.number,
            body: 'Successful: No critical vulnerabilities found. PR auto-merged.'
          })
